module.exports = {
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    backgroundColor: {
      'primary': '#472de8',
      'secondary': '#cee825',
      'white': '#ffffff',
      'gray':'#545454',
      'gray-light':'#ededed',
      'purple':'#643bed'
     },
    extend: {
      fontSize: {
        'tiny': '13px',
        'tiny-up':'0.938rem',
         'base': '18px',
         'lg': '20px',
         'xl': '23px',
         'x35': '35px',
         'x4': '40px',
         '2xl': '50px',
       },
       fontFamily: {
        'raleway': ['raleway'],
        'roboto': ['roboto'],
       },
       textColor: {
        'gray': '#545454',
        'black':'#282828',
        'green':'#cee825',
        'gray-light':'#afafaf'
      },
      spacing: {
        'hero-image-width': '67.5rem',
        'hero-image-height':'49rem',
        'marginLeft': '6.25rem',
        'portfolioSpace':'7rem',
        'heightPortfolio':'115rem',
        'heightPortfolioMobile':'180rem',
        'cardHeightPortfolio':'31.25rem',
        'heightH2Portfolio':'15.125rem',
        'heightHeaderAboutMe':'28rem',
        'marginSkills':'17.438rem',
        'widthSkillBackground':'19.125rem',
        'heightSkillBackground':'73rem',
        'lineWeight':'19rem',
        'detailHeight':'28.125rem',
        'portfolioBackgroundDetail':'36.375rem',
        'portfolioBackgroundDetailHeight':'27.75rem',
        'portFolioDescriptionWidth':'20rem',
        'portFolioDescriptionHeight':'39.5rem',
        'margin-portfolio':'4.688rem',
        'tecnologyWidth':'5.25rem',
        'heightPortfolioDetails':'47rem',
        'heightPortfolioDetailsMobil':'75rem',
      },
      backgroundImage:{
        'hero-image': "url('/src/assets/images/home/home-principal.png')",
        'company-wow': "url('/src/assets/images/home/companies/wow.png')",
        'company-playamia': "url('/src/assets/images/home/companies/playamia.png')",
        'company-trolley': "url('/src/assets/images/home/companies/trolley.png')",
        'company-wild': "url('/src/assets/images/home/companies/wildtours.png')",
        'company-mexicana': "url('/src/assets/images//home/companies/mexicana.png')",
        'company-logo-wow': "url('/src/assets/images/logos/logo-wow.png')",
        'company-logo-playamia': "url('/src/assets/images/logos/logo-pm.png')",
        'company-logo-trolley': "url('/src/assets/images/logos/logo-trolley.png')",
        'company-logo-wild': "url('/src/assets/images/logos/logo-wild.png')",
        'about-me-header': "url('/src/assets/images/aboutMe/header-about-me.png')",
        'portfolio-hero-wow': "url('/src/assets/images/portfolio/wow/background.png')",
        'portfolio-hero-mexicana': "url('/src/assets/images/portfolio/mexicana/background.png')",
        'portfolio-hero-playamia': "url('/src/assets/images/portfolio/playamia/background.png')",
        'portfolio-hero-trolley': "url('/src/assets/images/portfolio/trolley/background.png')",
        'portfolio-hero-wildtours': "url('/src/assets/images/portfolio/wildtours/background.png')",
        'portfolio-detail-wow': "url('/src/assets/images/portfolio/wow/detail-background.png')",
        'portfolio-detail-mexicana': "url('/src/assets/images/portfolio/mexicana/detail-background.png')",
        'portfolio-detail-playamia': "url('/src/assets/images/portfolio/playamia/detail-background.png')",
        'portfolio-detail-trolley': "url('/src/assets/images/portfolio/trolley/detail-background.png')",
        'portfolio-detail-wildtours': "url('/src/assets/images/portfolio/wildtours/detail-background.png')",
        'technology-jquery': "url('/src/assets/images/portfolio/technologies/jquery.png')",
        'technology-bootstrap': "url('/src/assets/images/portfolio/technologies/bootstrap.png')",
        'technology-html': "url('/src/assets/images/portfolio/technologies/html.png')",
        'technology-php': "url('/src/assets/images/portfolio/technologies/php.png')",
        'technology-css': "url('/src/assets/images/portfolio/technologies/css.png')",
        'technology-ionic': "url('/src/assets/images/portfolio/technologies/ionic.png')",
        'technology-laravel': "url('/src/assets/images/portfolio/technologies/laravel.png')",
        'technology-react': "url('/src/assets/images/portfolio/technologies/react.png')",
        'technology-redux': "url('/src/assets/images/portfolio/technologies/redux.png')",
        'technology-typescript': "url('/src/assets/images/portfolio/technologies/typescript.png')",
       },
       textAlign: ['initial', 'inherit'],
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
